INSERT INTO TB_EVENTS (NOME, LOCAL, DATE, HORARIO) VALUES ('BMW EXPIRENCE - EVENTO BRASIL','São Paulo','2022-10-12','12');
INSERT INTO TB_EVENTS (NOME, LOCAL, DATE, HORARIO) VALUES ('ROCK IN RIO','Rio de Janeiro','2022-12-12','12');
INSERT INTO TB_EVENTS (NOME, LOCAL, DATE, HORARIO) VALUES ('NEYMAR PARTY','Angra dos Reis','2022-10-24','20');
INSERT INTO TB_EVENTS (NOME, LOCAL, DATE, HORARIO) VALUES ('DEVS EVENTOS','São Paulo','2022-10-12','12');
INSERT INTO TB_EVENTS (NOME, LOCAL, DATE, HORARIO) VALUES ('PODCAST DEV','São Paulo','2022-10-12','12');